
services:
  # The .NET Web API Service
  # webapi:
  #   image: mysolution-webapi
  #   build:
  #     context: .
  #     dockerfile: MyWebApi/Dockerfile
  #   ports:
  #     - "5000:8080" # Maps localhost:5000 to container port 8080
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=mydb;Username=postgres;Password=mysecretpassword
  #   depends_on:
  #     database:
  #       condition: service_healthy # Wait for database health check before starting


  rabbitmq:
    image: docker-registry-002.zeuslearning.com/zeuslearning/rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol port for applications
      - "15672:15672" # HTTP Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis:latest
    container_name: redis_server
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} 
    volumes:
      - redis_data:/data
    

  # Database Dependency Service
  database:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql:latest
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

  redis_data:

  rabbitmq_data:

